AWSTemplateFormatVersion: '2010-09-09'
Description: 'grupo4_steven - VPC 10.4.0.0/16 + Bastion + Privada + NAT + S3 + SSM (AWS Academy)'

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.4.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: grupo4_steven-vpc

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: grupo4_steven-igw

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.4.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: grupo4_steven-public-subnet

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: grupo4_steven-public-rt

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  EIPNat:
    Type: AWS::EC2::EIP
    DependsOn: VPCGatewayAttachment
    Properties:
      Domain: vpc

  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt EIPNat.AllocationId
      SubnetId: !Ref PublicSubnet
      Tags:
        - Key: Name
          Value: grupo4_steven-nat

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.4.2.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: grupo4_steven-private-subnet

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway

  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet
      RouteTableId: !Ref PrivateRouteTable

  # Security Groups sin Ingress (Solo salida para SSM)
  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Bastion SG - SSM Only
      VpcId: !Ref VPC
      SecurityGroupIngress: [] 
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Private SG - SSM Only
      VpcId: !Ref VPC
      SecurityGroupIngress: []
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0b6c6ebed2801a5cb # Ubuntu 22.04 LTS apróx.
      InstanceType: t3.nano
      # KeyName eliminado: No se necesita para SSM
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref BastionSecurityGroup
      IamInstanceProfile: LabInstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update
          apt-get install -y unzip
          # El agente suele venir en Ubuntu, pero esto asegura que esté activo
          snap install amazon-ssm-agent --classic
          systemctl enable snap.amazon-ssm-agent.amazon-ssm-agent.service
          systemctl start snap.amazon-ssm-agent.amazon-ssm-agent.service
      Tags:
        - Key: Name
          Value: grupo4_steven-bastion

  PrivateInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0b6c6ebed2801a5cb
      InstanceType: t3.nano
      SubnetId: !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref PrivateSecurityGroup
      IamInstanceProfile: LabInstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update
          apt-get install -y mysql-client unzip
          snap install amazon-ssm-agent --classic
          systemctl enable snap.amazon-ssm-agent.amazon-ssm-agent.service
          systemctl start snap.amazon-ssm-agent.amazon-ssm-agent.service
      Tags:
        - Key: Name
          Value: grupo4_steven-privada

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "grupo4-steven-${AWS::AccountId}-${AWS::Region}"

Outputs:
  VpcId:
    Description: VPC ID
    Value: !Ref VPC

  VpcCidr:
    Description: VPC CIDR Block
    Value: !GetAtt VPC.CidrBlock

  PublicSubnetCidr:
    Description: Public Subnet CIDR
    Value: !GetAtt PublicSubnet.CidrBlock

  PrivateSubnetCidr:
    Description: Private Subnet CIDR
    Value: !GetAtt PrivateSubnet.CidrBlock

  NATGatewayEIP:
    Description: NAT Gateway EIP
    Value: !Ref EIPNat

  BastionInstanceId:
    Description: Bastion Instance ID
    Value: !Ref BastionHost

  BastionPublicIP:
    Description: Bastion Public IP
    Value: !GetAtt BastionHost.PublicIp

  BastionPrivateIP:
    Description: Bastion Private IP
    Value: !GetAtt BastionHost.PrivateIp

  PrivateInstanceId:
    Description: Private Instance ID
    Value: !Ref PrivateInstance

  PrivateInstanceIP:
    Description: Private Instance IP
    Value: !GetAtt PrivateInstance.PrivateIp

  S3BucketName:
    Description: S3 Bucket Name
    Value: !Ref S3Bucket

  S3BucketUrl:
    Description: S3 Bucket URL
    Value: !Sub 's3://${S3Bucket}'

  SSMCommandPrivate:
    Description: SSM Command for Private Instance
    Value: !Sub 'aws ssm start-session --target ${PrivateInstance} --region ${AWS::Region}'

  SSMCommandBastion:
    Description: SSM Command for Bastion
    Value: !Sub 'aws ssm start-session --target ${BastionHost} --region ${AWS::Region}'


